### ISSUE TITLE
tail -f 只能监控一个文件

### ISSUE THREAD

**Issue by feiyuyitiao** [wucao/websocket-tail-demo#1]
file: 
LogWebSocketHandle.java
line:24:
process = Runtime.getRuntime().exec("tail -f /var/log/syslog");
改为监控目录下的所有文件，如，存在目录/var/log/test：
process = Runtime.getRuntime().exec("tail -f /var/log/test/*");

问题：
启动服务，浏览器收不到websocket消息！

**Comment by wucao** [comment]
当然只能监控一个文件，这只是个DEMO，你可以基于这个开发监控多个文件。

**Comment by feiyuyitiao** [comment]
改写了下，新建一个脚本文件 tails.sh, 文件内容tail -f /var/log/test/\* 
LogWebSocketHandle.java 代码更改为： 
 URL resource = this.getClass().getResource("/");
 String cmd =resource.getPath()+ "tails.sh";
 process = Runtime.getRuntime().exec(cmd);
